Authentication Updates:
- Added and set up the mysqlStore in main
- switched `import process from 'process';` to `import * as process from 'process';` due to this error:
```
  console.log('process.env.HOST: ' + process.env.HOST);
                                             ^
TypeError: Cannot read properties of undefined (reading 'env')
    at bootstrap (\urban-dictionary-ar\backend\src\main.ts:17:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
- Updated the ESLint rules due to an `ESLint: Require statement not part of import statement` error
- Removed unnecessary import